#!/bin/sh
if [ $# -lt 3 ]; then
  echo "Not enough arguments: usage -> run begin_year end_year simulation_mnmonic"
  exit 1
fi
YEARN=$1
YEARL=$2
ENAM=$3
echo $ENAM > tmp
VERSION=`awk '{ n = split($1, parts, "_"); printf("%s", parts[1]) }' tmp`
SIM=`awk '{ n = split($1, parts, "_"); printf("%s", parts[n]) }' tmp`
eval YEARP=`expr $YEARN - 1`
\rm tmp
export YEARN YEARL YEARP ENAM VERSION SIM
echo $YEARN $YEARL $ENAM $VERSION $SIM
if [ ! -d ~/scratch/$ENAM ]; then
  mkdir ~/scratch/$ENAM
fi
cd ~/scratch/$ENAM
newlink () { if [ ! -f $2 ]; then ln -s $1 $2; fi }
recover () { if [ ! -f $2 ]; then cp -p $1 $2; fi }
choose () { if [ -f $1 ]; then cp $1 $3; else cp $2 $3 || exit 159; fi }
newlink ~e031/Input/V3.6/ahmcoef.nc ahmcoef.nc
newlink ~e031/Input/global_co2_merged_2019.txt atmco2.dat
newlink ~e031/Input/atmco2cfc.dat atmco2cfc.dat
newlink ~e031/Input/V3.6/bathy_level.nc bathy_level.nc
newlink ~e031/Input/V3.6/bathy_meter.nc bathy_meter.nc
newlink ~e031/e198Input/bathy.orca.nc bathy.orca.nc
newlink ~e031/Input/V3.6/coordinates.nc coordinates.nc
newlink ~e031/Input/V3.6/data_1m_potential_temperature_nomask.nc data_1m_potential_temperature_nomask.nc
newlink ~e031/Input/V3.6/data_1m_salinity_nomask.nc data_1m_salinity_nomask.nc
newlink ~e031/Input/V3.6/geothermal_heating.nc geothermal_heating.nc
newlink ~e031/Input/river.nc river.nc
newlink ~e031/e198Input/ndeposition.orca.nc ndeposition.nc
newlink ~e031/Input/V3.6/runoff_core_monthly.nc runoff_core_monthly.nc
newlink ~e031/Input/V3.6/K1rowdrg.nc K1rowdrg.nc
newlink ~e031/Input/V3.6/M2rowdrg.nc M2rowdrg.nc
newlink ~e031/Input/V3.6/chlorophyll.nc chlorophyll.nc
newlink ~e031/Input/V3.6/mask_itf.nc mask_itf.nc
newlink ~e031/Input/V3.6/EMPave_old.dat EMPave_old.dat
grep key_planktom10 ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then TOM=tom10
  else TOM=tom12
fi
grep key_trc_piic ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then PIIC=piic
fi
grep key_trc_dms ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then DMS=dms
fi
grep key_trc_n2o ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then N2O=n2o
fi
grep key_trc_ch4 ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then CH4=ch4
fi
grep key_c14b ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/cpp_ORCA2_LIM_PlankTOM.fcm > tmp
if [ -s tmp ]
  then C14=c14
  recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/atmc14.dat atmc14.dat
  recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/atmb14.dat atmb14.dat
  recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_c14b namelist_c14b
fi
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/iodef_${TOM}${PIIC}${DMS}${N2O}${CH4}${C14}.xml iodef.xml
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/field_def_${TOM}${PIIC}${DMS}${N2O}${CH4}${C14}.xml field_def.xml
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/domain_def.xml domain_def.xml
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_cfg namelist_cfg
if [ ! -f namelist_ref ]; then 
  sed s/1800/$YEARN/ ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_ref_ncep_start > namelist_ref
fi
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_ref_ncep namelist_ref_continue
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_ice_cfg namelist_ice_cfg
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_ice_ref namelist_ice_ref
  newlink ~e031/e198Input/dust.Jickells2005.times035.ORCA.nc dust.orca.nc
  recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist.trc.sms_${TOM} namelist.trc.sms
  if [ ! -f restart_trc_0000.nc ];then
    if [ -L restart_trc_0000.nc ];then echo 'broken restart_trc_0000.nc';exit;fi
    if [ $YEARP -lt 1947 ]
      then newlink /gpfs/home/e031/Input/restart_18991231_trc_GLODAPv2_O2Bianchi_PIC5.nc restart_trc.nc
#~e031/Input/restart_18991231_trc_GLODAPv2_mementoN2X_O2Bianchi_pPFTN.nc restart_trc.nc
      else newlink ~e031/Input/restart_19471231_trc_GLODAPv2_mementoN2X_O2Bianchi_pPFTN.nc restart_trc.nc
    fi
  fi
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_top_cfg namelist_top_cfg
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/namelist_top_ref_${TOM}${PIIC}${DMS}${N2O}${CH4}${C14} namelist_top_ref
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/dgom dgom
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/EXP00/run_totals.sh run_totals.sh
recover ~/nemo_v3.6/$VERSION/CONFIG/ORCA2_LIM_PlankTOM/BLD/bin/nemo.exe opa
recover /gpfs/software/xios-1.0/gcc/bin/xios_server.exe xios_server.exe
if [ -f rank001 ]; then rm rank* ; fi
if [ ! -f restart_0000.nc ];then
  if [ -L restart_0000.nc ];then echo 'broken restart_0000.nc';exit;fi
    if [ -f ~e031/Input/restart_${YEARP}1231_opa_obs_v3.6_ncep.nc ];then
  newlink ~e031/Input/restart_${YEARP}1231_opa_obs_v3.6_ncep.nc restart.nc
    else
  newlink ~e031/Input/restart_19191231_opa_obs_v3.6_ncep.nc restart.nc
#  sed "/nn_date0/ s/1979/${YEARN}/1" < namelist_ref > namelist_ref_continue
#  sed "/nn_rstctl/ s/2/0/1" < namelist_ref_continue > namelist_ref
    fi
fi
if [ ! -f restart_ice_in_0000.nc ];then
  if [ -L restart_ice_in_0000.nc ];then echo 'broken restart_ice_in_0000.nc';exit;fi
  newlink ~e031/Input/restart_ice_v3.6.nc restart_ice_in.nc
fi
LINK=$YEARN
while [ $LINK -le $YEARL ]; do
  if [ $LINK -lt 1948 ]; then
   newlink ~e031/Input/ncep_bulk_1948_1977_climatology.nc ncep_bulk_y${LINK}.nc
   newlink ~e031/Input/ncep_kelvin_1948_1977_climatology.nc ncep_kelvin_y${LINK}.nc
   newlink ~e031/Input/taux_1d_1948_1977_climatology.nc taux_1d_y${LINK}.nc
   newlink ~e031/Input/tauy_1d_1948_1977_climatology.nc tauy_1d_y${LINK}.nc
  else
   newlink /gpfs/data/greenocean/forcing/ncep/ncep_bulk_${LINK}.nc ncep_bulk_y${LINK}.nc
   newlink /gpfs/data/greenocean/forcing/ncep/ncep_kelvin_${LINK}.nc ncep_kelvin_y${LINK}.nc
   newlink /gpfs/data/greenocean/forcing/ncep/taux_1d_${LINK}.nc taux_1d_y${LINK}.nc
   newlink /gpfs/data/greenocean/forcing/ncep/tauy_1d_${LINK}.nc tauy_1d_y${LINK}.nc
  fi
  eval LINK=`expr $LINK + 1`
done
bsub -J${SIM}${YEARN} < dgom
if [ ! -f ${ENAM}.txt ]; then
  echo 'Describe this simulation' >> ${ENAM}.txt
  vi ${ENAM}.txt
fi
if [ ! -f code.tar ];then cd ~/nemo_v3.6/$VERSION/NEMO/ ; tar chf ~/scratch/$ENAM/code.tar */*90 */*/*90 */*/*/*90 ; fi
